/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package company;

import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author jj
 */
public class AnnouncementUpdate1 extends javax.swing.JPanel {

    DefaultTableModel model = null;
    int id;
    String idTable;

    /**
     * Creates new form UpdateAnnouncement
     */
    HomePageCompany parentframe;
    public AnnouncementUpdate1() {
        initComponents();
loadAnnouncementTable();
    }

    public AnnouncementUpdate1(int id1,HomePageCompany parentframe) {
        id = id1;
        initComponents();
        loadAnnouncementTable();
        this.parentframe=parentframe;

    }

    private void loadAnnouncementTable() {
        try {
            updateButton.setEnabled(false);
            deleteButton.setEnabled(false);

            Dbcon db = new Dbcon();
            ResultSet rs = db.select("select * from tbl_announcement where companyId='" + id + "' ");
            
            model = (DefaultTableModel) announcementTable.getModel();
            
            
            String arr [] = new String[3];
            
            while (rs.next()) {
                String id1 = rs.getString("id");
                String date = rs.getString("date");
                String post = rs.getString("post");
            
                arr[0] = id1;
                arr[1] = date;
                arr[2] = post;
                
                model.addRow(arr);
            }
            
        } catch (SQLException ex) {
            Logger.getLogger(AnnouncementUpdate1.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        announcementTable = new javax.swing.JTable();
        updateButton = new javax.swing.JButton();
        deleteButton = new javax.swing.JButton();

        addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                formFocusGained(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 153));
        jLabel1.setText("             JOB   ANNOUNCEMENT");

        announcementTable.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        announcementTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "Last Date", "Post"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        announcementTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                announcementTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(announcementTable);
        announcementTable.getColumnModel().getColumn(0).setMinWidth(0);
        announcementTable.getColumnModel().getColumn(0).setPreferredWidth(0);
        announcementTable.getColumnModel().getColumn(0).setMaxWidth(0);

        updateButton.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        deleteButton.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N
        deleteButton.setText("Delete");
        deleteButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(78, 78, 78)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 433, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(46, 46, 46)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(updateButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(35, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(updateButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(deleteButton)
                        .addGap(109, 109, 109))))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void announcementTableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_announcementTableMouseClicked
        model = (DefaultTableModel) announcementTable.getModel();
        if (model.getValueAt(announcementTable.getSelectedRow(), 0).toString().equals("")) {
            JOptionPane.showMessageDialog(this, "No data to select");
        } else {
            idTable = model.getValueAt(announcementTable.getSelectedRow(), 0).toString();
            updateButton.setEnabled(true);
            deleteButton.setEnabled(true);
        }        // TODO add your handling code here:
    }//GEN-LAST:event_announcementTableMouseClicked

    private void deleteButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteButtonActionPerformed
        String sql1 = "delete from tbl_announcement where id='" + idTable + "'";
        int n;
        Dbcon db = new Dbcon();
        n = db.insert(sql1);

        AnnouncementUpdate1 announcementUpdate1 = new AnnouncementUpdate1(id,parentframe);
        this.getParent().add(announcementUpdate1);
        this.setVisible(false);
        announcementUpdate1.setVisible(true);
        this.revalidate();
        this.repaint();


    }//GEN-LAST:event_deleteButtonActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed

        parentframe.setEnabled(false);
        HomePageCompany.flag = 1;
        AnnouncementUpdate2 announcementUpdate2 = new AnnouncementUpdate2(idTable,parentframe);
        
        announcementUpdate2.setVisible(true);
        
//        parentframe.getContentPane().removeAll();
//        parentframe.repaint();
//        parentframe.revalidate();

    }//GEN-LAST:event_updateButtonActionPerformed

    private void formFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_formFocusGained
        System.out.println("Hello");
        // TODO add your handling code here:
    }//GEN-LAST:event_formFocusGained
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable announcementTable;
    private javax.swing.JButton deleteButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
