/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package company;

import db.Dbcon;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.prefs.Preferences;
import javax.swing.JOptionPane;

/**
 *
 * @author jj
 */
public class LoginPageCompany extends javax.swing.JFrame {

    String name;
    String pass;

     final String PREF_REMEMBER_PASSWORD_COMPANY = "remember_password_company";
    final String PREF_USER_NAME_COMPANY = "p_user_name_company";
    final String PREF_PASSWORD_COMPANY = "p_password_company";
    //String newValue;
    
    Preferences prefs1 = Preferences.userNodeForPackage(LoginPageCompany.class);
    /**
     * Creates new form LoginPage
     */
    public LoginPageCompany() {
        initComponents();
        this.setLocationRelativeTo(null);
         getPreviousRememberdPassword();
    }
 private void getPreviousRememberdPassword() {
        String previosValues = prefs1.get(PREF_REMEMBER_PASSWORD_COMPANY, "false");
        if (previosValues.equals("true")) {
            rememberPasswordCheckBox.setSelected(true);
            String storedUserName = prefs1.get(PREF_USER_NAME_COMPANY, "");
            System.out.println(storedUserName);
            userNameTextField.setText(storedUserName);
            String storedPassword = prefs1.get(PREF_PASSWORD_COMPANY, "");
            passwordField.setText(storedPassword);
            System.out.println(storedPassword);
            
        } else {
            rememberPasswordCheckBox.setSelected(false);
        }
        System.out.println(previosValues);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        rememberPasswordCheckBox = new javax.swing.JCheckBox();
        userNameTextField = new javax.swing.JTextField();
        passwordField = new javax.swing.JPasswordField();
        loginButton = new javax.swing.JButton();
        clearButton = new javax.swing.JButton();
        registraionButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Trebuchet MS", 3, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 204));
        jLabel1.setText("LOGIN  PAGE");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(407, 27, 180, 34));

        jLabel2.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel2.setText("USER  NAME              :");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 94, 208, 26));

        jLabel4.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        jLabel4.setText("PASSWORD                :");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(242, 161, 208, 26));

        rememberPasswordCheckBox.setText("Rememer  Passwod");
        rememberPasswordCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rememberPasswordCheckBoxActionPerformed(evt);
            }
        });
        jPanel1.add(rememberPasswordCheckBox, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 221, 277, -1));

        userNameTextField.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        userNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userNameTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(userNameTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 94, 219, 26));
        jPanel1.add(passwordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 164, 219, 26));

        loginButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        loginButton.setText("Login");
        loginButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginButtonActionPerformed(evt);
            }
        });
        jPanel1.add(loginButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 275, -1, -1));

        clearButton.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        clearButton.setText("Clear");
        clearButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearButtonActionPerformed(evt);
            }
        });
        jPanel1.add(clearButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(565, 275, -1, -1));

        registraionButton1.setFont(new java.awt.Font("Berlin Sans FB", 0, 18)); // NOI18N
        registraionButton1.setText("Registration");
        registraionButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registraionButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(registraionButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(379, 333, 167, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/login2.png"))); // NOI18N
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, 240, 230));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 743, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 399, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void userNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_userNameTextFieldActionPerformed

private void loginButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginButtonActionPerformed
    try {
        name = userNameTextField.getText();
        pass = passwordField.getText();

        String sql = "select * from tbl_company where name='" + name + "' and password='" + pass + "'";
        ResultSet rs;
        Dbcon db = new Dbcon();
        rs = db.select(sql);
        if (rs.next()) {
              prefs1.put(PREF_USER_NAME_COMPANY, userNameTextField.getText());
            prefs1.put(PREF_PASSWORD_COMPANY, passwordField.getText());
            int id=rs.getInt("id");
            new HomePageCompany(id).setVisible(true);
            this.dispose();


        } else {
            JOptionPane.showMessageDialog(this, "User Name or Password incorrect");
            userNameTextField.setText("");
            passwordField.setText("");
        }
    } catch (SQLException ex) {
        Logger.getLogger(LoginPageCompany.class.getName()).log(Level.SEVERE, null, ex);
    }

}//GEN-LAST:event_loginButtonActionPerformed

    private void clearButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearButtonActionPerformed
        userNameTextField.setText("");
        passwordField.setText("");
    }//GEN-LAST:event_clearButtonActionPerformed

    private void rememberPasswordCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rememberPasswordCheckBoxActionPerformed

        

        boolean rememberPasssword = rememberPasswordCheckBox.isSelected();
        prefs1.put(PREF_REMEMBER_PASSWORD_COMPANY, rememberPasssword + "");
      
    }//GEN-LAST:event_rememberPasswordCheckBoxActionPerformed

    private void registraionButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registraionButton1ActionPerformed
            new Request().setVisible(true);
            this.dispose();        // TODO add your handling code here:
    }//GEN-LAST:event_registraionButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginPageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginPageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginPageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginPageCompany.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginPageCompany().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton clearButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton loginButton;
    private javax.swing.JPasswordField passwordField;
    private javax.swing.JButton registraionButton1;
    private javax.swing.JCheckBox rememberPasswordCheckBox;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables
}
